
<div class="col-md-12 main-content">
          <div class="post post-2 post-gallery single-post">
            <div class="post-head"><h3><?php echo $posts->posts_title ?></h3>
              <div class="post-meta">
                <div><i class="fa fa-user"></i>BY : <a href="#"><?php echo $user_datas[$posts->posts_user] ?></a></div>
                <div><i class="fa fa-clock-o"></i><?php echo date('d M Y',$posts->posts_date) ?></div>
                <div><i class="fa fa-comments"></i><a href="#"><?php echo $total_comments ?> Comments</a></div>
                <div><i class="fa fa-folder-open"></i>IN : 
                  <?php 
                  $arr = explode(',', $posts->posts_categories);
                  foreach ($arr as $key) {
                  ?>
                  <a href="<?php echo BASE_URL.'/categories/'.$categorie_datas[$key]['link'] ?>"><?php echo $categorie_datas[$key]['name'] ?></a>
                  <?php } ?>
                </div>
                <div><i class="fa fa-heart"></i><a href="#">77</a></div>
              </div><!-- End post-meta -->
              <div class="clearfix"></div>
            </div><!-- End post-head -->
            <div class="post-wrap">
              <div class="post-inner">
                  <?php echo $posts->posts_content ?>
                  
                <div class="clearfix"></div>
                <div class="post-share-view">
                  <div class="post-meta">
                    <div><i class="fa fa-eye"></i><span><?php echo $posts->posts_view ?> </span>Views</div>
                    <div class="post-meta-share">
                      <i class="fa fa-share-alt"></i>
                      <a href="#">Share This</a>
                      <div class="share-social">
                        <ul>
                          <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                          <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                          <li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                        <i class="fa fa-caret-down"></i>
                      </div><!-- End follow-social -->
                    </div>
                    <div class="post-tags">
                      <i class="fa fa-tags"></i>
                      Tags : 
                      <?php 
                      $arr = explode(',', $posts->posts_tags);
                      foreach ($arr as $key) {
                      ?>
                      <a href="<?php echo BASE_URL.'/tags/'.$tag_datas[$key]['link'] ?>"><?php echo $tag_datas[$key]['name'] ?></a>
                      <?php } ?>
                    </div>
                  </div><!-- End post-meta -->
                </div><!-- End post-share-view -->
                <div class="clearfix"></div>
              </div><!-- End post-inner -->
            </div><!-- End post-wrap -->
          </div><!-- End post -->
          
          <div class="page-navigation clearfix">
            <div class="nav-next"><a href="#"><i class="fa fa-angle-double-left"></i><span>Old Entries</span></a></div>
            <div class="nav-previous"><a href="#"><span>New Entries</span><i class="fa fa-angle-double-right"></i></a></div>
          </div><!-- End page-navigation -->
          
          <div class="height_20"></div>
          
          <div class="post post-2">
            <div class="post-author"><img alt="" src="images/about-img.png"></div>
            <div class="post-wrap">
              <div class="post-inner">
                <div class="post-title"><i class="fa fa-user"></i>2code</div>
                <p>Lorem ipsum dolor sit amet, mauris suspendisse viverra eleifend tortor tellus suscipit, tortor aliquet at nulla mus, dignissim neque, nulla neque. Ultrices proin mi urna nibh ut, aenean sollicitudin etiam libero nisl, ultrices ridiculus in magna purus consequuntur, ipsum donec orci ad vitae pede, id odio.</p>
                <div class="social-ul">
                  <ul>
                    <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li class="social-linkedin"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    <li class="social-youtube"><a href="#"><i class="fa fa-youtube-play"></i></a></li>
                  </ul>
                </div><!-- End social-ul -->
                <div class="clearfix"></div>
              </div><!-- End post-inner -->
            </div><!-- End post-wrap -->
          </div><!-- End post -->
          
          <div class="post related-posts-div">
            <div class="post-wrap">
              <div class="post-inner">
                <div class="post-title"><i class="fa fa-share"></i>Related Posts</div>
                <div class="row">
                  <div class="related-posts">
                    <div class="bx-wrapper" style="max-width: 1170px;">
                      <div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 239px;">
                        <ul style="width: 415%; position: relative; transition-timing-function: linear; transition-duration: 0s; left: -720px;">
                          <li style="float: left; list-style: none; position: relative; width: 720px;" class="bx-clone">
                            <div class="col-md-6 related-post-item">
                              <div class="related-post-one">
                                <div class="related-post-img">
                                  <a href="single-blog.html"><img alt="" src="images/post-small-3.png"></a>
                                  <div class="related-post-type"><i class="fa fa-youtube-play "></i></div>
                                </div>
                                <div class="related-post-head">
                                  <a href="single-blog.html">Awesome Youtube Post.</a>
                                  <span><i class="fa fa-clock-o"></i>August 20, 2014</span>
                                  <span><i class="fa fa-comments"></i><a href="#">85</a> Comments</span>
                                </div>
                              </div>
                            </div>
                            <div class="col-md-6 related-post-item">
                              <div class="related-post-one">
                                <div class="related-post-img">
                                  <a href="single-blog.html"><img alt="" src="images/post-small-1.png"></a>
                                  <div class="related-post-type"><i class="fa fa-image "></i></div>
                                </div>
                                <div class="related-post-head">
                                  <a href="single-blog.html">Awesome Image Post.</a>
                                  <span><i class="fa fa-clock-o"></i>August 20, 2014</span>
                                  <span><i class="fa fa-comments"></i><a href="#">85</a> Comments</span>
                                </div>
                              </div>
                            </div>
                          </li>
                        </ul>
                      </div>
                      <div class="bx-controls bx-has-pager bx-has-controls-direction">
                        <div class="bx-pager bx-default-pager">
                          <div class="bx-pager-item">
                            <a href="" data-slide-index="0" class="bx-pager-link active">1</a>
                          </div>
                          <div class="bx-pager-item">
                            <a href="" data-slide-index="1" class="bx-pager-link">2</a>
                          </div>
                        </div>
                        <div class="bx-controls-direction">
                          <a class="bx-prev" href=""></a>
                          <a class="bx-next" href=""></a>
                        </div>
                      </div>
                    </div>
                  </div><!-- End related-posts -->
                </div><!-- End row -->
                <div class="clearfix"></div>
              </div><!-- End post-inner -->
            </div><!-- End post-wrap -->
          </div><!-- End post -->
          
          <div class="post">
            <div class="post-wrap">
              <div class="post-inner">
                <div class="post-title"><i class="fa fa-comments"></i>Comments <span>( 5 )</span></div>
                <ol class="commentlist clearfix">
                    <li class="comment">
                        <div class="comment-body clearfix"> 
                            <div class="avatar"><img alt="" src="images/about-img.png"></div>
                            <div class="comment-text">
                                <div class="author clearfix">
                                  <div class="comment-meta">
                                        <span><a href="#">2code</a></span>
                                        <div class="date">August 20 , 2014 at 10:00 pm</div> 
                                    </div>
                                    <a class="comment-reply button" href="#">Reply</a>
                                </div>
                                <div class="text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi adipiscing gravida odio, sit amet suscipit risus ultrices eu. Fusce viverra neque at purus laoreet consequat. Vivamus vulputate posuere nisl quis consequat.</p>
                                </div>
                            </div>
                        </div>
                        <ul class="children">
                            <li class="comment">
                                <div class="comment-body clearfix"> 
                                  <div class="avatar"><img alt="" src="images/comment-img-1.png"></div>
                                    <div class="comment-text">
                                        <div class="author clearfix">
                                            <div class="comment-meta">
                                                <span>begha</span>
                                                <div class="date">August 20 , 2014 at 10:00 pm</div> 
                                            </div>
                                            <a class="comment-reply button" href="#">Reply</a>
                                        </div>
                                        <div class="text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi adipiscing gravida odio, sit amet suscipit risus ultrices eu. Fusce viverra neque at purus laoreet consequat. Vivamus vulputate posuere nisl quis consequat.</p>
                                        </div>
                                    </div>
                                </div>
                                <ul class="children">
                                    <li class="comment">
                                        <div class="comment-body clearfix"> 
                                            <div class="avatar"><img alt="" src="images/comment-img-2.png"></div>
                                            <div class="comment-text">
                                                <div class="author clearfix">
                                                    <div class="comment-meta">
                                                        <span>Johnny</span>
                                                        <div class="date">August 20 , 2014 at 10:00 pm</div> 
                                                    </div>
                                                    <a class="comment-reply button" href="#">Reply</a>
                                                </div>
                                                <div class="text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi adipiscing gravida odio, sit amet suscipit risus ultrices eu. Fusce viverra neque at purus laoreet consequat. Vivamus vulputate posuere nisl quis consequat.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                 </ul><!-- End children -->
                            </li>
                            <li class="comment">
                              <div class="comment-body clearfix"> 
                                      <div class="avatar"><img alt="" src="images/comment-img-1.png"></div>
                                      <div class="comment-text">
                                          <div class="author clearfix">
                                              <div class="comment-meta">
                                                  <span>begha</span>
                                                  <div class="date">August 20 , 2014 at 10:00 pm</div> 
                                              </div>
                                              <a class="comment-reply button" href="#">Reply</a>
                                          </div>
                                          <div class="text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi adipiscing gravida odio, sit amet suscipit risus ultrices eu. Fusce viverra neque at purus laoreet consequat. Vivamus vulputate posuere nisl quis consequat.</p>
                                          </div>
                                      </div>
                                  </div>
                            </li>
                        </ul><!-- End children -->
                    </li>
                </ol>
                <div class="clearfix"></div>
              </div><!-- End post-inner -->
            </div><!-- End post-wrap -->
          </div><!-- End post -->
          
          <div class="post">
            <div class="post-wrap">
              <div class="tabs comment">

                <input id="tab-1" type="radio" name="radio-set" class="tab-selector-1" checked="checked" />

                <label for="tab-1" class="tab-label-1"><i class="fa fa-facebook-square"></i>Facebook</label>

                 

                <input id="tab-2" type="radio" name="radio-set" class="tab-selector-2" />

                <label for="tab-2" class="tab-label-2"><i class="fa fa-google-plus-square"></i>Google +</label>

                <div class="clear-shadow"></div>

                 

                <div class="content-tab">

                  <div class="tab-1">

                    <div class="fb-comments" data-href="<?php echo $posts->posts_link ?>" data-width="650" data-numposts="15" data-colorscheme="light"></div>

                  </div>

                  <div class="tab-2">

                    <script src="https://apis.google.com/js/plusone.js"></script>

                    <div class="g-comments"data-href="<?php echo $posts->posts_link ?>"data-width="650" data-first_party_property="BLOGGER" data-view_type="FILTERED_POSTMOD"></div>

                  </div>

                </div>

              </div>
              <div class="post-inner">
                <div class="post-title"><i class="fa fa-comment"></i>Add Comment</div>
                <div class="comment-form">
                  <div class="form-input">
                    <i class="fa fa-user"></i>
                    <input type="text" placeholder="Your Name">
                  </div>
                  <div class="form-input">
                    <i class="fa fa-envelope"></i>
                    <input type="email" placeholder="Email">
                  </div>
                  <div class="form-input">
                    <i class="fa fa-home"></i>
                    <input type="url" placeholder="URL">
                  </div>
                  <div class="form-input">
                    <i class="fa fa-comment"></i>
                    <textarea placeholder="Comment"></textarea>
                  </div>
                  <input type="submit" class="button" value="Post Comment">
                </div>
                <div class="clearfix"></div>
              </div><!-- End post-inner -->
            </div><!-- End post-wrap -->
          </div><!-- End post -->
          
        </div>

<script>(function(d, s, id) {

var js, fjs = d.getElementsByTagName(s)[0];

if (d.getElementById(id)) return;

js = d.createElement(s); js.id = id;

js.src = "//connect.facebook.net/vi_VN/all.js#xfbml=1";

fjs.parentNode.insertBefore(js, fjs);

}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">

window.___gcfg = {lang: 'vi'};

 

(function() {

var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;

po.src = 'https://apis.google.com/js/platform.js';

var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);

})();

</script>