<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title><?php echo isset($title) ? $title : null ?></title>
  <meta http-equiv="content-language" content="vi" />
  
  <link rel="alternate" href="<?php echo BASE_URL ?>" hreflang="vi-vn" />
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/css/edit/style.css">
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/css/edit/bootstrap.min.css">
	<!-- <link rel="stylesheet" type="text/css" href="<?php BASE_URL ?>/css/edit/bootstrap-responsive.min.css"> -->
  <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/js/edit/ui/jquery-ui.css">
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery-1.7.2.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/ui/jquery-ui.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/html5.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery.form.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/custom.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/localization/messages_vi.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/bootstrap.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/bootstrap.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/colResizable-1.5.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery.stickyheader.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery.ba-throttle-debounce.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL ?>/js/edit/jquery.battatech.excelexport.js"></script>
  <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>/css/edit/component.css" />
  
<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-507e26a03bf7f1f7" async="async"></script>
<script src="<?php echo BASE_URL ?>/js/edit/pace.min.js"></script>
<style type="text/css">
  .pace {
  -webkit-pointer-events: none;
  pointer-events: none;

  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;

  overflow: hidden;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 2000;
  width: 100%;
  height: 5px;
  background: rgba(255, 255, 255, 0.69);
  box-shadow: 0 2px 10px 2px rgba(0, 0, 0, 0.6);
}

</style>
</head>

<body>
      
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

          <!-- Kiem tra dang nhap -->
          <?php 
          if ($_SESSION) {
            ?>
            <a class="logined" href="<?php echo $this->url('user/logout') ?>">&nbsp; | Logout</a><a class="logined" href="<?php echo BASE_URL.'/users/info/'.$_SESSION['userid_logined'] ?>"><b><i><?php echo $_SESSION['user_logined']; ?> </i></b></a>
            <?php
          }
          else{
            ?>
            <a class="logined" href="<?php echo $this->url('users/login') ?>">Login</a>
            <?php
          }
          ?>
          <!-- end -->
        </div>
      </div>
    </div>

    
    <div id="container">
    	
			<?php echo $content; ?>
      
            
        
    </div> <!-- /container -->
  </span>

  <div>
    <span style="font-size:5px">Powered by <a target="_blank" style="color:#fff" href="http://www.tinhoctainha.com">Dịch vụ Tin Học Tại Nhà</a></span>
  </div>
  </body>
</html>