<!doctype html> 
<!-- ========================================
Template: Tin Hoc Tai Nha
Version 1.0
Author: Ngo Ton
Email: ngoton.it@gmail.com
AuthorUrl: https://facebook.com/Ngoton.IT 
========================================= -->
   
<!--[if IE 6 ]><html lang="vi-VN" class="ie6"> <![endif]-->   
<!--[if IE 7 ]><html lang="vi-VN" class="ie7"> <![endif]-->   
<!--[if IE 8 ]><html lang="vi-VN" class="ie8"> <![endif]-->
<!--[if IE 9 ]><html lang="vi-VN" class="ie9"> <![endif]-->   
<!--[if (gt IE 9)|!(IE)]><!-->   
<html lang="vi-VN" class="no-js">   
  <!--<![endif]-->      
  <head>      
    <!-- ==============================================
             Title and basic Meta Tags
    =============================================== -->           
    <meta charset="utf-8">      
    <title><?php echo isset($title)?$title:'Programming, Network, Office, Hardware, Software, Design, Photography..' ?></title>      
    <meta name="viewport" content="width=device-width, initial-scale=1.0">      
    <meta name="description" content="Programming, Network, Office, Hardware, Software, Design, Photography">      
    <meta name="keywords" content="Programming, Network, Office, Hardware, Software, Design, Photography, Lập trình, Mạng máy tính, Phần cứng, Phần mềm, Tin học văn phòng, Thiết kế đồ họa">      
    <meta name="author" content="Tin Hoc Tai Nha">      
    <!-- ==============================================
     Mobile Metas
    =============================================== -->          
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">      
    <!-- ==============================================
             CSS
    =============================================== -->                       
    <link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL ?>/css/bootstrap.min.css">      
    <!-- <link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL ?>/css/style.css">    -->
    <link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL ?>/css/idangerous.swiper.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL ?>/css/font-awesome.min.css">  
    <!-- ==============================================
             Google Fonts
    =============================================== -->            
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,900' rel='stylesheet' type='text/css'>   
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,300' rel='stylesheet' type='text/css'>   

    <meta name="alexaVerifyID" content="mBKJ6__TfmWrx4NiF6lyliEMFmM"/>  
    <meta name="alexaVerifyID" content="opvrD78weRtAoTB7w93-nD30SRQ"/> 
    <link rel="shortcut icon" href="<?php echo ROOT_URL ?>/images/favicon.png">
    <!-- ==============================================
             Blog
    =============================================== -->   
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/reset.css"> <!-- CSS reset -->
    <link rel="stylesheet" href="<?php echo BASE_URL ?>/css/style.css"> <!-- CSS reset -->
    <script src="<?php echo BASE_URL ?>/js/modernizr.js"></script> <!-- Modernizr -->

  </head>   
<body class="preload">
   <!-- START Loading... -->              
   <div id="preload">
      <div id="preload-content">
         <div class="preload-bounce">                                  
            <span class="bounce1">               
            </span>                                  
            <span class="bounce2">               
            </span>                                  
            <span class="bounce3">               
            </span>                                   
            <span class="bounce4">               
            </span>                           
         </div>
      </div>
   </div>
   <!-- END Loading... -->
   <!-- Kenburn Slider Image-->
   <div id="kenburns-bg">
   </div>
   <!-- END Kenburn Slider Image-->
   <!-- Overlay -->             
   <div id="canvas" class="bg-overlay">
     <canvas></canvas> 
   </div>
   <!-- End Overlay -->          
   <!-- START wrapper -->
   <div class="wrapper">
      <!-- START HEADER -->        
      <header>
         <div class="header-bar header-top">
            <!-- Site Logo -->            
            <div class="logo">
               <a href="<?php echo ROOT_URL ?>">
               <img src="<?php echo ROOT_URL ?>/images/logo.png" title="Tin Hoc Tai Nha" />
               </a>
            </div>
            <!-- End Site Logo -->   
            <div class="right">
              <a href="#"><img src="<?php echo ROOT_URL ?>/images/flag_vi.png" title="Vietnamese" class="vi" /></a>
              <a href="#"><img src="<?php echo ROOT_URL ?>/images/flag_en.png" title="English" class="en" /></a>
            </div>                          
         </div>
         <div class="header-bar header-bottom" >
            <div class="clearfix footer-part">
               <div class="left-part">
                  <p class="copyright uppercase">                            
                     Copyright &copy;<?php echo date('Y') ?> Tin Hoc Tai Nha. All right reserved.                         
                  </p>
               </div>
               <div class="center-part">
                  <a href="http://qa.tinhoctainha.com" target="_blank"><i class="fa fa-question-circle"></i> Q&A</a>
               </div>
               <div class="right-part">
                  <div class="social">
                     <a target="_blank" href="https://www.facebook.com/tinhoctainha" class="tip-top" title="Facebook"><i class="fa fa-facebook"></i></a>
                     <a target="_blank" href="https://twitter.com/tinhoctainha" class="tip-top" title="Twitter"><i class="fa fa-twitter"></i></a>
                     <a target="_blank" href="https://plus.google.com/+TinhoctainhaVN" class="tip-top" title="G+"><i class="fa fa-google-plus"></i></a>
                     <a target="_blank" href="#" class="tip-top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                     <a target="_blank" href="https://www.linkedin.com/in/tinhoctainha" class="tip-top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                     <a target="_blank" href="https://www.flickr.com/photos/ngo-ton/albums/72157659653195478" class="tip-top" title="Flickr"><i class="fa fa-flickr"></i></a>
                     <a target="_blank" href="https://github.com/ngoton" class="tip-top" title="Github"><i class="fa fa-github"></i></a>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- END HEADER -->
      <div class="swiper-container">
         <div class="swiper-wrapper">
            <!-- START BLOG -->
            <div class="swiper-slide about">
               <div class="content slide-content">
                  <div class="container">
                       <?php echo $content ?>
                   </div>
                </div>    

            </div>
         </div>
      </div>
      <!-- END blog -->
                         
    </div>
   <!-- END swiper-wrapper -->    
  </div>
<!-- END swiper-container -->          
</div>
<!-- END wrapper -->
   <!-- ==============================================
      JS
      =============================================== -->   
      

   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/jquery.min.js"></script>                   
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/bootstrap.min.js"></script>   
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/plugins.js"></script>             
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/idangerous.swiper.min.js"></script>
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/jquery.appear.js"></script>         
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/star.js"></script>                   
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/gmap-settings.js"></script> 
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/jquery.velocity.min.js"></script>
   <script type="text/javascript" src="<?php echo ROOT_URL ?>/js/jquery.kenburnsy.min.js"></script>         
   <script type="text/javascript" src="<?php echo BASE_URL ?>/js/init.js"></script>   

   <script src="js/main.js"></script> <!-- Resource jQuery -->
   
   <script type="text/javascript">
 function change_one(){
    document.getElementById('htmlFiveBox').style.opacity = "0.2";
   }
function back_one(){
    document.getElementById('htmlFiveBox').style.opacity = "1";
   }
function change_two(){
    document.getElementById('htmlFiveBox').style.opacity = "0.2";
    document.getElementById('psdDesignBox').style.opacity = "0.2";
   }
function back_two(){
    document.getElementById('htmlFiveBox').style.opacity = "1";
    document.getElementById('psdDesignBox').style.opacity = "1";
   }
function change_three(){
    document.getElementById('htmlFiveBox').style.opacity = "0.2";
    document.getElementById('psdDesignBox').style.opacity = "0.2";
    document.getElementById('javaBox').style.opacity = "0.2";
   }
function back_three(){
    document.getElementById('htmlFiveBox').style.opacity = "1";
    document.getElementById('psdDesignBox').style.opacity = "1";
    document.getElementById('javaBox').style.opacity = "1";
   }
function change_four(){
    document.getElementById('htmlFiveBox').style.opacity = "0.2";
    document.getElementById('psdDesignBox').style.opacity = "0.2";
    document.getElementById('javaBox').style.opacity = "0.2";
    document.getElementById('logoDesignBox').style.opacity = "0.2";
   }
function back_four(){
    document.getElementById('htmlFiveBox').style.opacity = "1";
    document.getElementById('psdDesignBox').style.opacity = "1";
    document.getElementById('javaBox').style.opacity = "1";
    document.getElementById('logoDesignBox').style.opacity = "1";
   }
function change_five(){
    document.getElementById('htmlFiveBox').style.opacity = "0.2";
    document.getElementById('psdDesignBox').style.opacity = "0.2";
    document.getElementById('javaBox').style.opacity = "0.2";
    document.getElementById('logoDesignBox').style.opacity = "0.2";
    document.getElementById('printingBox').style.opacity = "0.2";
   }
function back_five(){
    document.getElementById('htmlFiveBox').style.opacity = "1";
    document.getElementById('psdDesignBox').style.opacity = "1";
    document.getElementById('javaBox').style.opacity = "1";
    document.getElementById('logoDesignBox').style.opacity = "1";
    document.getElementById('printingBox').style.opacity = "1";
   }
 </script>       
 <style type="text/css">
    .right{
      float:right;
    }
    .right a img.vi {
        opacity: 1;
        transition: all 1s;
        -webkit-transition: all 1s;
    }
    .right a img.en {
        opacity: 0.4;
        transition: all 1s;
        -webkit-transition: all 1s;
    }
    .right a:hover img {
        opacity: 1;
        transition: all 1s;
        -webkit-transition: all 1s;
    }
 </style>    
</body>
</html>